name: bm_tecno_lab
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  cloud_firestore: ^4.13.1
  dio: ^5.3.3
  # firebase_auth: ^4.14.0
  # flutter_local_notifications: ^16.1.0
  # flutter_riverpod: ^2.4.6
  # flutter_secure_storage: ^9.0.0
  # app_settings: ^5.1.1
  # intl: ^0.18.1
  # url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText-Regular.ttf

 